<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-01-19 01:16

$extensionPath = t3lib_extMgm::extPath('phpunit');
return array(
	'tx_phpunit_cli_phpunit' => $extensionPath . 'class.tx_phpunit_cli_phpunit.php',
	'tx_phpunit_database_testcase' => $extensionPath . 'class.tx_phpunit_database_testcase.php',
	'tx_phpunit_testcase' => $extensionPath . 'class.tx_phpunit_testcase.php',
	'tx_phpunit_testlistener' => $extensionPath . 'class.tx_phpunit_testlistener.php',
	'tx_phpunit_module1' => $extensionPath . 'mod1/class.tx_phpunit_module1.php',
	'tx_phpunit_module1_ajax' => $extensionPath . 'mod1/class.tx_phpunit_module1_ajax.php',
	'tx_phpunit_report_status' => $extensionPath . 'report/class.tx_phpunit_report_status.php',
	'tx_phpunit_test_testcase' => $extensionPath . 'Tests/tx_phpunit_test_testcase.php',
	'tx_phpunit_test_testsuite' => $extensionPath . 'Tests/tx_phpunit_testsuite.php',
);
?>