---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 3 * * 1'
jobs:
  php-lint:
    name: "PHP linter"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2
          coverage: none
      - name: "Show Composer version"
        run: composer --version
      - name: "Show the Composer configuration"
        run: composer config --global --list
      - name: "Run PHP lint"
        run: "composer ci:php:lint"
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
  code-quality:
    name: "Code quality checks"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2
          coverage: none
      - name: "Show Composer version"
        run: composer --version
      - name: "Show the Composer configuration"
        run: composer config --global --list
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v3
        with:
          key: "php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php${{ matrix.php-version }}-composer-\n"
      - name: "Install Composer dependencies"
        run: "composer install --no-progress"
      - name: "Run command"
        run: "composer ci:${{ matrix.command }}"
    strategy:
      fail-fast: false
      matrix:
        command:
          - "php:sniff"
          - "php:fixer"
          - "php:stan"
        php-version:
          - "8.1"
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-22.04
    needs: php-lint
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel_tags
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      DATABASE_HOST: 127.0.0.1
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: typo3
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2
          extensions: mysqli
          coverage: none
      - name: "Show Composer version"
        run: composer --version
      - name: "Show the Composer configuration"
        run: composer config --global --list
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v3
        with:
          key: "php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php${{ matrix.php-version }}-composer-\n"
      - name: "Install TYPO3 Core"
        env:
          TYPO3: "${{ matrix.typo3-version }}"
        run: |
          composer require --no-progress typo3/cms-core:"$TYPO3"
          composer show
      - name: "Set up TYPO3"
        run: >
          .Build/vendor/bin/typo3cms install:setup --no-interaction --site-setup-type="site"
          --database-user-name="${DATABASE_USER}" --database-host-name="${DATABASE_HOST}"
          --database-port="${{ job.services.mysql.ports[3306] }}" --database-name="${DATABASE_NAME}"
          --admin-user-name="admin" --admin-password="password" --site-name="Test installation";
      - name: "Run unit tests"
        run: "composer ci:tests:unit"
    strategy:
      fail-fast: false
      matrix:
        include:
          - typo3-version: "^9.5"
            php-version: "7.2"
          - typo3-version: "^9.5"
            php-version: "7.3"
          - typo3-version: "^9.5"
            php-version: "7.4"
          - typo3-version: "^10.4"
            php-version: "7.2"
          - typo3-version: "^10.4"
            php-version: "7.3"
          - typo3-version: "^10.4"
            php-version: "7.4"
          - typo3-version: "^11.5"
            php-version: "7.4"
          - typo3-version: "^11.5"
            php-version: "8.0"
          - typo3-version: "^11.5"
            php-version: "8.1"
          - typo3-version: "^11.5"
            php-version: "8.2"
